// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using trabfinal.Data;

#nullable disable

namespace trabfinal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427012000_AddComentariosLugares")]
    partial class AddComentariosLugares
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("trabfinal.Models.ComentarioLugar", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("Calificacion").HasColumnType("INTEGER");
                    b.Property<DateTime>("FechaPublicacion").HasColumnType("TEXT");
                    b.Property<int>("LugarId").HasColumnType("INTEGER");
                    b.Property<string>("Texto").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("UsuarioId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("UsuarioId");
                    b.ToTable("ComentariosLugares");
                });

            modelBuilder.Entity("trabfinal.Models.InscripcionEvento", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("EventoId").HasColumnType("INTEGER");
                    b.Property<DateTime>("FechaRegistro").HasColumnType("TEXT");
                    b.Property<int>("UsuarioId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("UsuarioId", "EventoId").IsUnique();
                    b.ToTable("InscripcionesEventos");
                });

            modelBuilder.Entity("trabfinal.Models.Tarea", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<bool>("Completada").HasColumnType("INTEGER");
                    b.Property<string>("Descripcion").HasColumnType("TEXT");
                    b.Property<DateTime>("FechaCreacion").HasColumnType("TEXT");
                    b.Property<DateTime?>("FechaLimite").HasColumnType("TEXT");
                    b.Property<string>("Materia").HasColumnType("TEXT");
                    b.Property<string>("Prioridad").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime?>("Recordatorio").HasColumnType("TEXT");
                    b.Property<string>("Titulo").IsRequired().HasColumnType("TEXT");
                    b.Property<int?>("UsuarioId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("UsuarioId");
                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("trabfinal.Models.Usuario", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Carrera").HasColumnType("TEXT");
                    b.Property<string>("Email").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Nombre").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Password").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("trabfinal.Models.ComentarioLugar", b =>
                {
                    b.HasOne("trabfinal.Models.Usuario", "Usuario")
                        .WithMany("ComentariosLugares")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("trabfinal.Models.InscripcionEvento", b =>
                {
                    b.HasOne("trabfinal.Models.Usuario", "Usuario")
                        .WithMany("InscripcionesEventos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("trabfinal.Models.Tarea", b =>
                {
                    b.HasOne("trabfinal.Models.Usuario", "Usuario")
                        .WithMany("Tareas")
                        .HasForeignKey("UsuarioId");
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("trabfinal.Models.Usuario", b =>
                {
                    b.Navigation("ComentariosLugares");
                    b.Navigation("InscripcionesEventos");
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
